### ISSUE TITLE
Rate and add notes to Pomodoro

### ISSUE THREAD

**Issue by dracan** [dracan/tomatoad#30]
User should be able to add a note to a pomodoro for their future reference.

**Comment by dracan** [comment]
To expand on this, when you first start a Pomodoro, a window should appear asking the user to enter text summarising what they'd like to achieve in this Pomodoro. Then when that Pomodoro completes, a second window should pop up asking them what they _actually_ achieved. This second window should also show the text the user entered from the start of that Pomodoro.

It's important to reflect on what was achieved in a Pomodoro to maximize the benefit. This _journalling_ of Pomodoros can help with this.

There should be a setting to not do this, as some users might find this annoying.

**Comment by dracan** [comment]
Also, would be good if on that second window, the user can _rate_ the Pomodoro. Perhaps have a 5-star rating control that they can click on. I'll update this issue now to reflect this.

**Comment by Odonno** [comment]
Or something like the upvotes system of Medium?

**Comment by Odonno** [comment]
@dracan Not necessarily, The advantage is that you only one button to push. And it gives you a single number to store as simple as having a star-rating system. The thing is to find the best rating system for Pomodori.

**Comment by dracan** [comment]
@Odonno Doesn't that mean you'd have to press that one button multiple times to have a higher rating? What would be the maximum? This doesn't really feel like the correct use-case for something like this to be honest. There's no defined and obviously max rating either for an up-voting system, so it's not clear what you'd rate an awesomely focussed pomodoro where you got lots done. For a 5-star system, it would be obviously to just click the full 5 stars....

![](http://ridesharegenius.com/wp-content/uploads/2015/03/5-stars-640x162.jpg)

The main idea behind this is that sometimes when I finish a Pomodoro, whilst I haven't been distracted as such - I sometimes feel that it wasn't a great one, either due to not being as fully in the zone as I'd have liked, or not getting as much done as I'd liked. This just means that I can rate the pomodoro as such. Whereas, sometimes I get a pomodoro, where I'm completely in the zone, get _loads_ done, and am really buzzing at the end of it. So it's nice to be able to rate this as such too.

**Comment by dracan** [comment]
Re. notes: if a pomodoro is restarted or interrupted, then the note popup when you start your next pomdoro should be pre-populated with the same text. A lot of the time, you probably want to type similar.
