### ISSUE TITLE
Idea: Linking Pomodoros to Tasks

### ISSUE THREAD

**Issue by lukemerrett** [dracan/tomatoad#31]
* As a user I can view a list of tasks
* As a user I can add a task to a list
* As a user I can delete a task on a list
* As a user I can modify a task on a list
* As a user I can mark 1 task as "active", so pomodoros are tracked against it
* As a user I can see how many pomodoros a task has taken thus far
* As a user I can mark a task as complete
* As a user I can see a list of completed tasks

**Comment by dracan** [comment]
To be honest, this is probably out of scope for what I envisage Tomotoad being. I don't really see it as a task management app - but more a _focus_ aid. Issue #18 will allow tagging pomodoros, so this will allow some form of categorisation.

**Comment by lukemerrett** [comment]
The tagging functionality sounds worthwhile, be interested to see how it plays out, could tie it into the analytics in #32 (work pomodoros v.s personal project pomodoros for example).

Happy this is closed if out of scope @dracan

**Comment by dracan** [comment]
Cool, will close then.
