### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by dracan** [dracan/tomatoad#35]
Need some form of release notes that user can easily go to when getting an update.

**Comment by gep13** [comment]
@dracan have you played with GitReleaseManager?  It would allow you to automatically create a set of releasenotes, based on the assigned labels and milestones on GitHub.

**Comment by dracan** [comment]
@gep13 I haven't yet - but I've seen it in the list of Cake built-in addons - so was planning to have a play :)

**Comment by gep13** [comment]
Nice! Let me know if you have any questions about how it works.  It is my default tool now for creating release notes for projects that I work on.  It does mean that you need to add a small amount of "process" to the repository for it to work, but looks like you are following at least part of it with how you are using the issues you are opening just now.

**Comment by dracan** [comment]
I've updated GitReleaseManager.yaml to generate release notes. Before closing this, add a right-click context menu option to visit the release notes page in Github directly from the app.
