### ISSUE TITLE
Investiate development platforms

### ISSUE THREAD

**Issue by dracan** [dracan/tomatoad#5]
Whilst I'd rather do this in .NET  - it would be nice to be cross platform. So Electron is looking the most suitable candicate.

Another option is [Avalonia](https://github.com/AvaloniaUI/Avalonia), which was suggested on Twitter by @gep13.

**Comment by dracan** [comment]
A few other options based on a Google search (basically because I'd much rather do it in .NET):

* [Electron.NET](https://github.com/ElectronNET/Electron.NET/) ([tutorial blog post](http://www.cross-platform-blog.com/electron.net/electron.net-musicplayer-app-with-asp.net-core/))
* [Eto](https://github.com/picoe/Eto)
* [DevZH.UI](https://github.com/noliar/DevZH.UI) + [libui](https://github.com/andlabs/libui)

**Comment by dracan** [comment]
I also worry that it could look more ugly by making it xplat, and will also open up more maintenance work and require me to start testing on all 3 platforms. Personally, I only care about it being on Windows. It would be nice to be xplat - but I have a feeling that I might regret it.

**Comment by dracan** [comment]
Although, just been playing around with Electron, and this is pretty easy and looks really nice. Whilst I really wanted to do this in .NET - if it's going to be xplat - this feels like a really good solution. Took me about a minute to add a _tomato_ system tray icon...

![image](https://user-images.githubusercontent.com/567988/34466597-337e282c-eed1-11e7-8793-95bc7eccc411.png)

**Comment by dracan** [comment]
Right - going to go with this. Means it's xplat, so is usable by more people. Looks pretty nice xplat - I mean, vscode! It also gives me an excuse to play with Electron, as I've been meaning to do so for a while.

**Comment by Odonno** [comment]
Interested in your dev stack. So I suppose you will go with a web stack? Which one ? (javascript/typescript? and angular/react/vue or pure vanilla?)

**Comment by dracan** [comment]
@Odonno As simple as possible. It's primarily going to have the following components ...

* System Tray icon (showing countdown), with rightclick menu
* Settings dialogbox
* Floating window showing countdown (optionally visible by user)

I'm new to Electron, by background is .NET - both web and desktop. Electron feels the best choice though - so I'm currently doing a bit of reading / Pluralsighting on Electron before architecting it. I have Angular experience though - so if non-vanilla makes sense, this is the most likely. Also, if Typescript is do-able - definitely.

**Comment by dracan** [comment]
@Odonno Also, will look into Vue to see if this makes sense too. Been hearing _a lot_ about this recently - so definitely want to see what all the fuss is about! I believe it's more lightweight too - so might work well.

**Comment by Odonno** [comment]
Good to know. Seems not too much UI. Currently, the most hype framework is Inferno: a React-like library of 9kb which is the fastest framework (after vanillajs of course).

No current experience in vuejs. May also be a good time to start. :)

Anyway, I let you dig into it.
