### ISSUE TITLE
GitReleaseManager.yml isn't being used

### ISSUE THREAD

**Issue by dracan** [dracan/tomatoad#69]
Looks like my `GitReleaseManager.yml` isn't being used. When I added it, I wasn't sure if it would be loaded automatically by convention, or if I needed to explicitly reference it. Looks like it's the latter.

**Comment by gep13** [comment]
@dracan fairly sure that GRM is looking for `GitReleaseManager.yaml` not `GitReleaseManager.yml`.  It should probably be updated to look for both.

**Comment by dracan** [comment]
@gep13 Ah, that makes sense. I wasn't sure if it should be loaded automagically, or if needed to be explicitly referenced anyway. I noticed when publishing this morning that it failed due to my `refactor` label on an issue which is covered in my GitReleaseManager yaml file - so I just created this ticket without looking further into it. So should it by design just look in the current folder for the file and just magically work? Ie. the filename extension is most likely the issue I'm experiencing?

**Comment by gep13** [comment]
Yes, GRM will automagically pick up the YAML file, but it does expect it to be named specifically, and I am fairly sure that is the problem that you are running into.

**Comment by gep13** [comment]
Yeah, looks like it is specific:

https://github.com/GitTools/GitReleaseManager/blob/1923bd87b4c9caee2e884e65281056d02d6210f3/Source/GitReleaseManager/Configuration/ConfigurationProvider.cs#L76

**Comment by dracan** [comment]
Cool - renamed it then :) Thanks for the spot!
